// ProjectsSection.jsx
import { useState } from 'react';
import { useEffect } from 'react';

import ProjectCard from '@/components/ProjectCard/ProjectCard.jsx';
import ProjectDetail from '@/components/ProjectDetail/ProjectDetail.jsx'; // New component for the expanded view

import timeTravelerImage from '@/assets/timeTraveler.png';
import timeTravelerVideo from '@/assets/TimeTraveler.mp4';
import emissionsTrackerImage from '@/assets/emissionsTracker.png';
import FSMIMage from '@/assets/FSM.svg';
import formBuilderVideo from '@/assets/formBuilder.mp4';
import formBuilderImage from '@/assets/formBuilder.png';

import styles from './ProjectsSection.module.css';

const projectsData = [
  {
    id: 'time', 
    title: 'Time Traveler', 
    summary: 'Travel into the future with this fun personal project, built using VanillaJS with a Node.JS backend',
    videoPath: timeTravelerVideo,
    image: timeTravelerImage,

    techStack: ['Javascript', 'Node.js', 'Express'],
    fullDesc: 'A sci-fi themed project based on the theory of time dilation, the time traveler project allows the user to input a travel speed (as a percentage of the speed of light) and a duration to travel into the future and get a generated response to what the world will be like in the year they return. It leverages Node.js and Express to setup and call the ChatGPT API in order to return a custom response related to the users inputs. The concept also demanded advanced CSS styling and handling of complex mathematical equations using Javascript.',
    keyLearning: [
        {category: 'API key protection', body: 'Successfully implemented a secure proxy server using Node.js and Express to call the external ChatGPT API, ensuring the sensitive API key was hidden from the client-side and only used on the server.'},
        {category: 'Secure environment variables', body: 'Utilized environment variables (e.g., .env files) to store and manage the API key, following best practices for production deployment and source control security.'},
        {category: 'Request/Response Handling', body: 'Gained experience in managing the complete lifecycle of an API call, including securely forwarding client requests to the external API and parsing the complex JSON response before sending a simplified result back to the client.'},
        {category: 'CSS Animation & Motion', body: 'Implemented custom CSS keyframe animations and transitions to create realistic movement that contribute to the project visual theme without relying on heavy JavaScript libraries.'},
        {category: 'Responsive Theming', body: 'Ensured the complex visual theme and layout remained fully responsive and maintained aesthetic integrity across various viewport sizes.'}
    ]
},

  {
    id: 'emissions',
    title: 'Journey Emissions',
    summary: 'Calculate the emissions on your planned journey, built using VanillaJS with a Node.JS backend',
    image: emissionsTrackerImage,

    techStack: ['Javascript', 'Node.js', 'Express'],
    fullDesc: 'The emissions tracker application allows the user to input a journey and vehicle to calculate the emissions generated by the journey. It leverages both Node.js and express to handle calling both the Google Maps and DVLA APIs to calculate the required information to pass back to the user.',
    keyLearning: [
        {category: 'Multi-API Integration', body: 'Successfully integrated and orchestrated data from two distinct external APIs (DVLA and Google Maps) within a single, unified Node.js/Express API.'},
        {category: 'Data Aggregation and Transformation', body: 'Developed server-side logic to combine disparate data sources (e.g., vehicle data from DVLA and distance/route data from Google Maps) into a cohesive dataset required for the final emissions calculation.'},
        {category: 'API Key Management', body: 'Reinforced proficiency in utilizing a secure proxy server via Express to protect sensitive API keys, ensuring they were stored as environment variables and never exposed to the client.'},
        {category: 'Branding Compliance', body: 'Successfully designed and implemented a user interface (UI) that adheres strictly to the organization branding guidelines, demonstrating the ability to integrate design constraints into development workflow.'},
        {category: 'Complex Data Presentation', body: 'Designed intuitive methods for presenting the calculated emissions data and journey details clearly to the user, ensuring the final output was easy to understand.'}
    ]
},

  {
    id: 'fsm',
    title: 'Fire Safety Manual',
    summary: 'A mission-critical application built on PowerApps where all transactional logic is delegated to the SQL Server backend.',
    image: FSMIMage,

        techStack: ['PowerApps', 'SQL/ T-SQL', 'Git', 'Azure DevOps Pipelines', 'VS Code', 'Database DevOps'],
        fullDesc: 'This enterprise application manages a complex internal workflow to organise and clarify the fire safety requirements expected of a project (e.g., document tracking, approvals, responsibilities). The PowerApps canvas app acts purely as a presentation layer, focusing on UI/UX, while all business rules, transactional integrity, and data validation are executed via stored procedures and direct database logic in the connected SQL Server instance. This design minimizes the risk of inconsistent data entry and maximizes the performance of the PowerApps application by keeping the canvas logic extremely lightweight.',
        keyLearning: [
        {
            category: 'Database CI/CD Implementation', 
            body: 'Successfully created and implemented a process using VS Code and DevOps Repos to bring Git version control to stored procedures. The process utilized an Azure DevOps pipeline to automatically execute SP deployments against the DEV database upon code merge.'
        },
        {
            category: 'Automated Unit Testing for DB Logic', 
            body: 'Designed and implemented unit test scripts to validate the integrity of the stored procedures. These scripts executed all CRUD (Create, Read, Update, Delete) operations simultaneously, returning a clear pass/fail result for each test, ensuring high-quality deployments.'
        },
        {category: 'Database Logic Decoupling', body: 'Successfully engineered an architecture where the PowerApp acted as a passive conduit, with all transaction handling and business rule enforcement pushed down to the secure, scalable database layer.'},
        {category: 'Performance and Security', body: 'Improved performance by allowing the database engine to execute complex T-SQL logic efficiently, and enhanced security by preventing end-users from directly manipulating complex business rules via the low-code interface.'},
        {category: 'Thin-Client Development', body: 'Gained experience in designing front-end flows optimized for interacting solely with database stored procedures, focusing on streamlined input/output rather than complex in-app data manipulation.'}
    ]
},

{
    id: 'form-builder-poc',
    title: 'Dynamic Form Builder POC',
    summary: 'A proof-of-concept application demonstrating a serverless, dynamic form builder using React, Vite, and Firestore for schema and submission handling.',
    videoPath: formBuilderVideo,
    image: formBuilderImage,

    techStack: ['React', 'Vite', 'Firestore'],
    fullDesc: 'The Dynamic Form Builder is a full-stack proof-of-concept allowing users to visually define form schemas (fields, types, labels, validation). These schemas are stored in Firestore, and the application dynamically renders the corresponding forms. All submitted data is then saved back to a separate collection in Firestore, demonstrating end-to-end data flow using a serverless architecture. This fills a gap in the organisation for an external data collection tool that could be branded professionally and handles more complex forms and validation for higher quality data (Microsoft Forms im looking at you).',
    keyLearning: [
        {category: 'Firestore Integration & Modeling', body: 'Successfully implemented Firestore as a core serverless database to manage two distinct data models: static form definitions (schemas) and dynamic user submissions.'},
        {category: 'Dynamic Component Rendering', body: 'Developed a robust system in React to parse JSON form schemas retrieved from the database and translate them into corresponding UI components (e.g., text inputs, dropdowns) at runtime.'},
        {category: 'Secure Data Handling', body: 'Gained hands-on experience setting up Firestore Security Rules to govern read/write access, ensuring that form definitions are public while submission data is securely tied to authenticated users (via anonymous sign-in).'},
        {category: 'State Management Complexity', body: 'Managed complex state flow for dynamic form inputs, ensuring user input correctly maps back to its schema definition before being stored in the database.'},
        {category: 'Full-Stack Serverless Architecture', body: 'Achieved a complete full-stack, serverless application using only React, Vite, and Google Firestore, demonstrating proficiency in modern development paradigms.'}
    ]
}
];

const ProjectsSection = () => {
    const [activeProjectId, setActiveProjectId] = useState(null);

    // Find the project data if an ID is active
    const activeProject = projectsData.find(p => p.id === activeProjectId);

    const handleClose = () => setActiveProjectId(null);

    // 🌟 1. FIX THE JUMPING ISSUE HERE 🌟
    useEffect(() => {
        if (activeProjectId) {
            // Add class to body when modal is open
            document.body.classList.add('modal-open');
        } else {
            // Remove class when modal is closed
            document.body.classList.remove('modal-open');
        }
        
        // Cleanup function runs when component unmounts or dependency changes
        return () => {
            document.body.classList.remove('modal-open');
        };
    }, [activeProjectId]);


    return (
        // 2. ALWAYS RETURN THE PARENT SECTION
        <section id="projects" className="section-full-height">
            <div className="content-container"> {/* Use your content container class here */}
                <h2 className={styles.stylingH2}>My Work</h2>
                <p>All work showcased below adheres to modern, scalable architectural principles.This structure reflects my commitment to building high-quality, maintainable solutions across the entire technical stack.</p>
                <p className={styles.stylingP}><b>Click on a project to find out more</b></p>
                
                {/* 3. ALWAYS RENDER THE GRID */}
                <div className={styles.projectsGrid}>
                    {projectsData.map(project => (
                        <ProjectCard 
                            key={project.id}
                            project={project}
                            onClick={setActiveProjectId}
                        />
                    ))}
                </div>
            </div>
            
            {/* 4. CONDITIONALLY RENDER THE MODAL/DETAIL VIEW (as an overlay) */}
            {activeProject && (
                <ProjectDetail project={activeProject} onClose={handleClose} />
            )}
        </section>
    );
};

export default ProjectsSection;